name: Mirror to readme.com repo
on:
  push:
    branches:
      - main
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Push main → v1.0 on readme repo
        run: |
          git remote add destination git@github.com:LicLens/readme.git
          git push destination refs/remotes/origin/main:refs/heads/v1.0 --force
